project:
  type: website
  resources: 
    - "img"

website:
  title: "plusSixOne"
  favicon: "favicon.ico"
  image: "profile.png"
  navbar:
    logo: "profile.png"
    left:
      - text: "AFLM"
        menu:
          - pages/aflm-predictions.qmd
          - pages/aflm-games.qmd
          - pages/aflm-model-results.qmd
      - text: "AFLW"
        menu: 
          - pages/aflw-coming-soon.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jimmyday12
      - icon: twitter
        href: https://twitter.com/plusSixOneBlog
format:
  html:
    theme:
      light: minty
      dark: darkly
    css: styles.css

editor: visual

