project:
  type: website
  resources: 
    - "image"

website:
  title: "plusSixOne Blog"
  navbar:
    right:
      - about.qmd
      - text: "AFLM"
        menu:
          - pages/aflm-predictions.qmd
          - pages/aflm-games.qmd
          - pages/aflm-model-results.qmd
      - text: "AFLW"
        menu: 
          - pages/aflw-coming-soon.qmd
      - icon: github
        href: https://github.com/jimmyday12
      - icon: twitter
        href: https://twitter.com/plusSixOneBlog
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

