project:
  type: website

website:
  title: "plusSixOne Blog"
  navbar:
    right:
      - about.qmd
      - text: "AFLM"
        menu:
          - aflm-predictions.qmd
          - current-tips.qmd
          - model-results.qmd
      - text: "AFLW"
        menu: 
          - aflw.qmd
      - icon: github
        href: https://github.com/jimmyday12
      - icon: twitter
        href: https://twitter.com/plusSixOneBlog
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

