project:
  type: website
  resources:
    -"/images/"

website:
  title: "plusSixOne Blog"
  navbar:
    right:
      - about.qmd
      - text: "AFLM"
        menu:
          - aflm-predictions.qmd
          - aflm-games.qmd
          - aflm-model-results.qmd
      - text: "AFLW"
        menu: 
          - aflw-coming-soon.qmd
      - icon: github
        href: https://github.com/jimmyday12
      - icon: twitter
        href: https://twitter.com/plusSixOneBlog
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

