on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: "0 5,8,11,14 * * 4,5,6,0,1"

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
          
      - name: Install system Dependencies
        run: >
          sudo apt-get update && sudo apt-get install --yes
          libcurl4-openssl-dev
          libharfbuzz-dev
          libfribidi-dev
          libfreetype6-dev
          libpng-dev
          libtiff5-dev
          libjpeg-dev

      - name: Install R Dependencies from R env
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 3

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
